import { useEffect, useRef, useState } from "react";
import { AdminConfirmDialog } from "../AdminConfirmDialog";
import { mutateAdminCustomer } from "../../../services/adminCustomersV2Service";
import { customerStatuses, type CustomerIdentity, type CustomerMutation, type CustomerStatus } from "../../../types/adminCustomers";
import type { Coupon } from "../../../types";
import { MoreButton, ResourceState } from "./CustomerResource";
import { useAdminCustomerAudit } from "../../../hooks/useAdminCustomerAudit";
import { dateLabel } from "../../../lib/adminCustomersV2";

export function CustomerAdministration({ customer, coupons, onChanged, onBusy }: { customer: CustomerIdentity; coupons: Coupon[]; onChanged: () => void; onBusy: (busy: boolean) => void }) {
  const resource = useAdminCustomerAudit(customer.id);
  const [note, setNote] = useState(""), [tags, setTags] = useState(""), [status, setStatus] = useState<CustomerStatus>(customer.status || "active"), [hidden, setHidden] = useState(customer.hidden), [reason, setReason] = useState(""), [points, setPoints] = useState(""), [couponId, setCouponId] = useState("");
  const [confirmation, setConfirmation] = useState<{ title: string; operation: CustomerMutation } | null>(null), [pending, setPending] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const inFlight = useRef(false);
  useEffect(() => { if (resource.data) { setNote(resource.data.note); setTags(resource.data.tags.join(", ")); } }, [resource.data]);
  useEffect(() => { setStatus(customer.status || "active"); setHidden(customer.hidden); }, [customer.status, customer.hidden]);
  const base = { customerId: customer.id, expectedRevision: resource.data?.revision ?? -1 };
  const disabled = pending || resource.pending || !resource.data || !!resource.error;
  async function save(operation: CustomerMutation) {
    if (inFlight.current) return; inFlight.current = true; setPending(true); onBusy(true); setError(""); setMessage("");
    try { await mutateAdminCustomer(operation); setConfirmation(null); setMessage("Modification enregistrée et journalisée."); resource.reload(); onChanged(); }
    catch (cause) { const text = cause instanceof Error ? cause.message : "Enregistrement impossible."; setError(text); throw cause; }
    finally { inFlight.current = false; setPending(false); onBusy(false); }
  }
  function confirmStatus(nextStatus: CustomerStatus, archived: boolean) {
    setConfirmation({ title: archived ? "Archiver ce client" : customer.archived ? "Restaurer ce client" : "Confirmer le changement de statut", operation: { ...base, kind: "status", status: nextStatus, archived, hidden, expectedStatus: customer.status, expectedArchived: customer.archived, expectedHidden: customer.hidden, reason } });
  }
  return <div className="space-y-6"><ResourceState pending={resource.pending} error={resource.error} onRetry={resource.reload} />{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error} La saisie est conservée. En cas de conflit, rechargez la fiche puis vérifiez les valeurs.</p>}{message && <p role="status" className="text-forest">{message}</p>}
    <fieldset disabled={disabled} className="min-w-0 space-y-6">
      <section className="space-y-3"><h3 className="text-lg font-semibold">Notes et tags privés</h3><p className="text-sm text-ink/65">Réservés à l’administration. Révision {resource.data?.revision ?? "Non disponible"} · {dateLabel(resource.data?.updatedAt || null)}</p><label className="block text-sm">Note interne privée<textarea rows={5} maxLength={4000} className="input-field mt-1 w-full" value={note} onChange={(event) => setNote(event.target.value)} /></label><label className="block text-sm">Tags, séparés par une virgule<input className="input-field mt-1 w-full" value={tags} onChange={(event) => setTags(event.target.value)} /></label><button type="button" className="btn-primary" onClick={() => void save({ ...base, kind: "metadata", note, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) }).catch(() => {})}>Sauvegarder la note et les tags</button></section>
      {customer.historicalNote && <section className="rounded-xl bg-amber-50 p-4"><h3 className="font-semibold">Note historique</h3><p className="mt-2 whitespace-pre-wrap text-sm">{customer.historicalNote}</p><p className="mt-2 text-xs text-amber-900">Cette ancienne note provient du profil client et peut être lisible par son propriétaire. Elle est préservée sans migration automatique.</p></section>}
      {!!customer.promos?.length && <section className="space-y-2"><h3 className="font-semibold">Codes promo attribués pour suivi</h3><ul>{customer.promos.map((promo, index) => <li key={`${promo.code}-${index}`} className="text-sm">{promo.code} · {promo.isActive ? "actif" : "inactif"} · {dateLabel(promo.assignedAt)}</li>)}</ul></section>}
      <section className="space-y-3 border-t border-forest/10 pt-5"><h3 className="text-lg font-semibold">Statut et archivage</h3><label className="block text-sm">Motif de l’action<input maxLength={500} className="input-field mt-1 w-full" value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="flex flex-wrap items-center gap-3"><label className="text-sm">Statut<select className="input-field ml-2" value={status} onChange={(event) => setStatus(event.target.value as CustomerStatus)}>{customerStatuses.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm"><input type="checkbox" checked={hidden} onChange={(event) => setHidden(event.target.checked)} /> Masquer dans les listes actives</label><button type="button" className="btn-secondary" disabled={!reason.trim()} onClick={() => confirmStatus(status, status === "archived")}>Préparer le changement</button><button type="button" className="btn-secondary" disabled={!reason.trim()} onClick={() => confirmStatus(customer.archived ? "active" : "archived", !customer.archived)}>{customer.archived ? "Restaurer" : "Archiver"}</button></div></section>
      <section className="space-y-3 border-t border-forest/10 pt-5"><h3 className="text-lg font-semibold">Anciennes capacités commerciales</h3><p className="text-sm text-ink/65">Les points historiques restent distincts de la cagnotte. L’attribution d’un code est un suivi interne ; elle ne réserve pas le coupon à ce client.</p><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Nouveau solde de points<input type="number" min="0" step="1" className="input-field ml-2" value={points} onChange={(event) => setPoints(event.target.value)} /></label><button type="button" className="btn-secondary" disabled={customer.points === null || !reason.trim() || !points.trim() || !Number.isSafeInteger(Number(points)) || Number(points) < 0} onClick={() => setConfirmation({ title: "Confirmer le solde de points historiques", operation: { ...base, kind: "points", expectedPoints: customer.points!, targetPoints: Number(points), reason } })}>Préparer la correction des points</button></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Code promo<select className="input-field ml-2" value={couponId} onChange={(event) => setCouponId(event.target.value)}><option value="">Choisir</option>{coupons.filter((coupon) => coupon.isActive && !coupon.isArchived).map((coupon) => <option key={coupon.id} value={coupon.id}>{coupon.code}</option>)}</select></label><button type="button" className="btn-secondary" disabled={!couponId || !reason.trim()} onClick={() => setConfirmation({ title: "Confirmer l’attribution du code promo", operation: { ...base, kind: "promo", couponId, reason } })}>Préparer l’attribution</button></div></section>
    </fieldset>
    <section className="border-t border-forest/10 pt-5"><h3 className="mb-3 text-lg font-semibold">Journal des nouvelles actions V2</h3><ResourceState pending={resource.pagePending} error={resource.pageError} onRetry={() => void resource.loadMore()} empty={!resource.pending && !resource.error && resource.audit.items.length === 0} /><ul className="space-y-3">{resource.audit.items.map((entry) => <li key={entry.id} className="rounded-xl bg-cream p-4 text-sm"><p className="font-semibold">{entry.action} · {dateLabel(entry.date)}</p><p>Admin : {entry.adminUid}</p>{entry.reason && <p>Motif : {entry.reason}</p>}<p className="mt-2 break-words text-xs">Avant : {JSON.stringify(entry.before)} · Après : {JSON.stringify(entry.after)}</p></li>)}</ul><MoreButton cursor={resource.audit.nextCursor} pending={pending || resource.pending || resource.pagePending} onClick={() => void resource.loadMore()} /></section>
    <AdminConfirmDialog open={!!confirmation} title={confirmation?.title || "Confirmer"} description="L’opération sera vérifiée et journalisée côté serveur." summary={confirmation && <p>{customer.name || customer.email || customer.id} · {confirmation.operation.kind === "metadata" ? "" : confirmation.operation.reason}</p>} pending={pending} confirmDisabled={disabled} onCancel={() => setConfirmation(null)} onConfirm={() => confirmation ? save(confirmation.operation) : undefined} />
  </div>;
}
