export const collections = {
  products: "products",
  categories: "categories",
  orders: "orders",
  customers: "customers",
  stockMovements: "stockMovements",
  deliveryZones: "deliveryZones",
  coupons: "coupons",
  invoices: "invoices",
  counters: "counters",
  loyaltyMovements: "loyaltyMovements",
  settings: "settings",
  adminUsers: "adminUsers",
  supplierProducts: "supplierProducts",
  labReports: "labReports",
} as const;
