import { deepEqual, equal, ok, rejects } from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Firestore, Transaction } from "firebase-admin/firestore";
import { connectCagnotteEmulator, CAGNOTTE_DEMO } from "./cagnotteEmulator.js";
import { executeMarketingOperation, getMarketingContext, handleMarketingAdmin, MarketingError, marketingBusinessFingerprint, validateMarketingParameters } from "../api/_server/marketingAdmin.js";
import { FirebaseIdTokenVerificationError } from "../api/_server/adminAuth.js";
import { createContest, transitionContest } from "../api/_server/contests.js";
import type { VercelRequestLike, VercelResponseLike } from "../api/_server/http.js";
import type { MarketingAction, MarketingKind, MarketingParameters, MarketingReferences, MarketingResult } from "../src/types/marketing.js";
import type { ContestInput } from "../src/types/contests.js";
const db = await connectCagnotteEmulator(CAGNOTTE_DEMO);
const actor = "marketing-fixture-admin"; const now = new Date("2026-09-28T12:00:00.000Z");
let checks = 0; let contestPeriod = 0;
const test = async (name: string, run: () => Promise<unknown>) => { await run(); checks++; console.log(`PASS ${name}`); };
const code = () => `FIXTURE_${randomUUID().replaceAll("-", "").toUpperCase()}`;
const contestInput = (): ContestInput => { const start = now.getTime() + (++contestPeriod * 20 * 86400000); return { title: "Concours fixture", slug: `fixture-${randomUUID()}`, description: "Description du concours privé de test.", prizeValue: 30, prizeType: "store_credit", startAt: new Date(start).toISOString(), endAt: new Date(start + 7 * 86400000).toISOString(), drawAt: new Date(start + 8 * 86400000).toISOString(), rulesText: "Règlement de test suffisamment long.", eligibilityConditions: "Majeurs uniquement.", prizeExpirationDays: 30 }; };
function params(kind: MarketingKind): MarketingParameters {
  return { ...(["promotion", "campaign"].includes(kind) ? { promotion: { code: code(), label: "Promotion fixture", discountType: "percent" as const, discountValue: 10, minimumOrder: 20, promotionType: "percentage_cart_discount" as const, autoApply: false, priority: 0, stackable: true, isArchived: false, isTemplate: false } } : {}), ...(["banner", "campaign"].includes(kind) ? { banner: { title: "Bannière fixture", message: "Message admin de test.", type: "shop_card" as const, placement: "shop" as const, placements: ["shop" as const, "home" as const], priority: 10, variant: "promo" as const, dismissible: true, buttonLabel: "Voir la boutique", buttonUrl: "/boutique", isArchived: false, isTemplate: false } } : {}), ...(kind === "contest" ? { contest: contestInput() } : {}) };
}
async function setup(kind: MarketingKind = "promotion", parameters = params(kind), references: MarketingReferences = {}) {
  const baseFingerprints: Record<string, string> = {};
  for (const [key, id] of Object.entries(references)) { const collection = key === "couponId" ? "coupons" : key === "bannerId" ? "promoBanners" : "contests"; const data = (await db.collection(collection).doc(id).get()).data()!; baseFingerprints[key] = marketingBusinessFingerprint(key as keyof MarketingReferences, data); }
  const operation = { action: "save" as const, operationId: randomUUID(), draftId: randomUUID(), expectedRevision: 0, kind, title: "Brouillon fixture", parameters, references, baseFingerprints };
  return { result: await executeMarketingOperation(db, actor, operation, now), operation };
}
function step(result: MarketingResult, action: MarketingAction, operationId = randomUUID()) { return executeMarketingOperation(db, actor, { action, draftId: result.draft.id, expectedRevision: result.draft.revision, operationId }, now); }
async function approved(kind: MarketingKind = "promotion", parameters = params(kind), refs: MarketingReferences = {}) { const f = await setup(kind, parameters, refs); return step(await step(f.result, "review"), "approve"); }
async function materialized(kind: MarketingKind = "promotion", parameters = params(kind), refs: MarketingReferences = {}) { return step(await approved(kind, parameters, refs), "materialize"); }
const invalid = (code: string) => (e: unknown) => e instanceof MarketingError && e.code === code;
async function sizes(collections: string[]) { return Promise.all(collections.map(async (collection) => (await db.collection(collection).get()).size)); }
async function api(token: string, method = "GET", operation?: unknown) {
  let status = 200; let payload: unknown;
  const response = { setHeader() {}, status(value: number) { status = value; return this; }, json(value: unknown) { payload = value; } };
  await handleMarketingAdmin({ method, url: "/api/admin-contests?action=marketing", headers: token ? { authorization: `Bearer ${token}` } : {}, body: { operation } } as VercelRequestLike, response as unknown as VercelResponseLike, { db, verify: async (value) => { if (value === "invalid") throw new FirebaseIdTokenVerificationError("authentication"); return { uid: value, email: null }; } });
  return { status, payload };
}
try {
  await db.collection("adminUsers").doc(actor).set({ isActive: true });
  await db.collection("products").doc("marketing-product").set({ name: "Produit cadeau fixture", isActive: true, category: "flowers", stock: 100 });
  await test("brouillons manuels des quatre types : zéro effet public, participants, gains ou emails", async () => { const collections = ["coupons", "promoBanners", "contests", "contestEntries", "contestDraws", "contestPrizes", "contestAuditLogs"]; const before = await sizes(collections); for (const kind of ["promotion", "banner", "contest", "campaign"] as const) { const f = await setup(kind); equal(f.result.draft.origin, "manual"); equal(f.result.draft.authorId, actor); equal(f.result.draft.state, "draft"); equal(f.result.draft.revision, 1); } deepEqual(await sizes(collections), before); });
  await test("brouillon incomplet conservé en privé, revue invalide sans objet créé", async () => { const f = await setup("promotion", { promotion: { ...params("promotion").promotion!, code: "", label: "" } }); await rejects(step(f.result, "review"), invalid("invalid_draft")); equal(f.result.draft.state, "draft"); });
  await test("revue puis approbation de N : auteur et date serveur, aucune matérialisation implicite", async () => { const f = await setup(); await rejects(step(f.result, "approve"), invalid("review_required")); const reviewed = await step(f.result, "review"); const a = await step(reviewed, "approve"); equal(a.draft.reviewedRevision, 1); equal(a.draft.approvedRevision, 1); equal(a.draft.approval?.actorId, actor); ok(a.draft.approval?.at.endsWith("Z")); deepEqual(a.draft.references, {}); });
  await test("édition N+1 invalide l'approbation et l'activation de N", async () => { const a = await approved(); const edit = await executeMarketingOperation(db, actor, { action: "save", operationId: randomUUID(), draftId: a.draft.id, expectedRevision: 1, title: "Version modifiée", parameters: { promotion: { ...a.draft.parameters.promotion!, discountValue: 15 } } }, now); equal(edit.draft.revision, 2); equal(edit.draft.approvedRevision, undefined); equal(edit.draft.state, "draft"); await rejects(step(a, "materialize"), invalid("stale_revision")); await rejects(step(edit, "activate"), invalid("approval_required")); });
  await test("matérialisation explicite inactive puis activation explicite", async () => { const f = await setup(); await rejects(step(f.result, "materialize"), invalid("approval_required")); const m = await materialized(); const ref = db.collection("coupons").doc(m.draft.references.couponId!); equal((await ref.get()).data()?.isActive, false); equal((await ref.get()).data()?.usedCount, 0); equal(m.draft.materializedRevision, 1); const a = await step(m, "activate"); equal(a.draft.state, "activated"); equal((await ref.get()).data()?.isActive, true); equal((await ref.get()).data()?.priority, 0); equal((await ref.get()).data()?.stackable, true); });
  await test("rejeu de sauvegarde après réponse perdue : même brouillon et même révision", async () => { const f = await setup(); const replay = await executeMarketingOperation(db, actor, f.operation, now); equal(replay.replayed, true); deepEqual(replay.draft, f.result.draft); await rejects(executeMarketingOperation(db, actor, { ...f.operation, title: "Autre demande" }, now), invalid("operation_conflict")); await rejects(executeMarketingOperation(db, "other-admin", f.operation, now), invalid("operation_conflict")); });
  await test("matérialisation et activation rejouées : une seule écriture et audit par opération", async () => { const a = await approved("campaign"); const mid = randomUUID(); const m = await step(a, "materialize", mid); deepEqual((await step(a, "materialize", mid)).draft, m.draft); const id = randomUUID(); const first = await step(m, "activate", id); const coupon = db.collection("coupons").doc(m.draft.references.couponId!); await coupon.update({ usedCount: 7 }); const replay = await step(m, "activate", id); equal(replay.replayed, true); deepEqual(replay.draft, first.draft); equal((await coupon.get()).data()?.usedCount, 7); equal((await db.collection("marketingAuditLogs").doc(id).get()).data()?.action, "activate"); await rejects(step(first, "activate"), invalid("approval_required")); });
  await test("double clic concurrent même UUID : un seul résultat de campagne", async () => { const m = await materialized("campaign"); const id = randomUUID(); const results = await Promise.all([step(m, "activate", id), step(m, "activate", id)]); equal(results.filter((r) => r.replayed).length, 1); deepEqual(results[0].draft.references, results[1].draft.references); });
  await test("deux activations concurrentes avec UUID différents : une seule réussit", async () => { const m = await materialized(); const results = await Promise.allSettled([step(m, "activate"), step(m, "activate")]); equal(results.filter((r) => r.status === "fulfilled").length, 1); });
  await test("usedCount conserve les utilisations survenues après la lecture admin", async () => { const id = `counter-${randomUUID()}`; const p = params("promotion").promotion!; await db.collection("coupons").doc(id).set({ ...p, isActive: true, usedCount: 12, serverExtra: "preserved" }); const a = await approved("promotion", { promotion: { ...p, label: "Nouvelle configuration", discountValue: 17, startsAt: "2026-09-28T12:30:00Z" } }, { couponId: id }); const ref = db.collection("coupons").doc(id); await ref.update({ usedCount: 19 }); const m = await step(a, "materialize"); equal((await ref.get()).data()?.label, p.label); await step(m, "activate"); equal((await ref.get()).data()?.usedCount, 19); equal((await ref.get()).data()?.serverExtra, "preserved"); equal((await ref.get()).data()?.label, "Nouvelle configuration"); });
  await test("compteurs et état actif ne sont jamais acceptés dans la configuration client", async () => { for (const field of ["usedCount", "isActive", "source", "contestPrizeId"] as const) await rejects(setup("promotion", { promotion: { ...params("promotion").promotion!, [field]: field === "source" ? "contest" : 99 } }), invalid("server_field")); });
  await test("limite d'utilisation atteinte au dernier instant : activation refusée", async () => { const m = await materialized("promotion", { promotion: { ...params("promotion").promotion!, maxUses: 3 } }); await db.collection("coupons").doc(m.draft.references.couponId!).update({ usedCount: 3 }); await rejects(step(m, "activate"), invalid("max_uses")); equal((await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()?.isActive, false); });
  await test("désactivation et archivage gardent le compteur et journalisent l'auteur", async () => { const a = await step(await materialized(), "activate"); const ref = db.collection("coupons").doc(a.draft.references.couponId!); await ref.update({ usedCount: 5 }); const d = await step(a, "deactivate"); equal((await ref.get()).data()?.isActive, false); equal((await ref.get()).data()?.usedCount, 5); equal(d.draft.approvedRevision, undefined); const ar = await step(d, "archive"); equal(ar.draft.state, "archived"); equal((await ref.get()).data()?.isArchived, true); equal((await ref.get()).data()?.usedCount, 5); await rejects(step(ar, "review"), invalid("archived_draft")); });
  await test("conflit de configuration métier après validation détecté", async () => { const m = await materialized(); await db.collection("coupons").doc(m.draft.references.couponId!).update({ discountValue: 33 }); await rejects(step(m, "activate"), invalid("business_conflict")); });
  await test("code modifié : ancienne réservation libérée, provenance et compteur préservés", async () => { const original = await step(await materialized(), "activate"); const id = original.draft.references.couponId!; const ref = db.collection("coupons").doc(id); const oldCode = original.draft.parameters.promotion!.code; await ref.update({ source: "legacy", usedCount: 4 }); const m = await materialized("promotion", { promotion: { ...original.draft.parameters.promotion!, code: code() } }, { couponId: id }); const a = await step(m, "activate"); equal((await ref.get()).data()?.usedCount, 4); equal((await ref.get()).data()?.source, "legacy"); await step(a, "deactivate"); const reuse = await materialized("promotion", { couponDocumentId: `reuse-${randomUUID()}`, promotion: { ...params("promotion").promotion!, code: oldCode } }); ok(reuse.draft.references.couponId); });
  await test("produit supprimé ou inactif : validation puis revalidation finale bloquent", async () => { const f = await setup("promotion", { promotion: { ...params("promotion").promotion!, productIds: ["missing-product"] } }); await rejects(step(f.result, "review"), invalid("product_missing")); const m = await materialized("promotion", { promotion: { ...params("promotion").promotion!, productIds: ["marketing-product"] } }); await db.collection("products").doc("marketing-product").update({ isActive: false }); await rejects(step(m, "activate"), invalid("product_missing")); await db.collection("products").doc("marketing-product").update({ isActive: true }); });
  await test("sept règles conservées : fixes, pourcentages, livraison, seuil et cadeaux", async () => { for (const type of ["fixed_cart_discount", "fixed_category_discount", "threshold_extra_discount", "percentage_cart_discount", "percentage_category_discount", "free_shipping", "tiered_product_gift"] as const) { const base = params("promotion").promotion!; const p = { ...base, promotionType: type, discountType: type.startsWith("percentage") ? "percent" as const : type === "free_shipping" ? "free_shipping" as const : "fixed" as const, discountValue: type === "tiered_product_gift" || type === "free_shipping" ? 0 : 10, eligibleCategory: "flowers" as const, categories: ["flowers" as const], paidThresholdAmount: 40, maxGiftAmount: 5, maxDiscountAmount: 15, minEligibleSubtotal: 20, maxUses: 30, ...(type === "tiered_product_gift" ? { autoApply: true, giftTiers: [{ id: "t1", minimumSubtotal: 30, quantityGrams: 3 }, { id: "t2", minimumSubtotal: 50, quantityGrams: 5 }], giftProductIds: ["marketing-product"], defaultGiftProductId: "marketing-product", qualifyingScope: "products" as const, qualifyingProductIds: ["marketing-product"], giftSelectionMode: "customer_choice" as const } : {}) }; const m = await materialized("promotion", { promotion: p }); await step(m, "activate"); const saved = (await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()!; equal(saved.promotionType, type); equal(saved.maxDiscountAmount, 15); equal(saved.stackable, true); if (type === "tiered_product_gift") deepEqual(saved.giftTiers, p.giftTiers); } });
  await test("remises, catégories et paliers invalides rejetés par les validateurs existants", async () => { for (const p of [{ ...params("promotion").promotion!, discountValue: 101 }, { ...params("promotion").promotion!, categories: ["unknown"] }, { ...params("promotion").promotion!, promotionType: "tiered_product_gift", discountType: "fixed", discountValue: 0, giftTiers: [{ id: "t1", minimumSubtotal: 10, quantityGrams: 1.5 }], giftProductIds: ["marketing-product"] }]) { const f = await setup("promotion", { promotion: p as NonNullable<MarketingParameters["promotion"]> }); await rejects(step(f.result, "review"), invalid("invalid_draft")); } });
  await test("dates UTC normalisées, période future et expiration finales", async () => { const m = await materialized("promotion", { promotion: { ...params("promotion").promotion!, startsAt: "2026-09-29T00:30:00+02:00", endsAt: "2026-09-29T02:30:00+02:00" } }); equal(m.draft.parameters.promotion?.startsAt, "2026-09-28T22:30:00.000Z"); await step(m, "activate"); const config = (await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()!; equal(config.isActive, true); const expired = await materialized("promotion", { promotion: { ...params("promotion").promotion!, endsAt: "2026-09-27T12:00:00Z" } }); await rejects(step(expired, "activate"), invalid("expired")); const invalidPeriod = await setup("promotion", { promotion: { ...params("promotion").promotion!, startsAt: "2026-09-30T12:00:00Z", endsAt: "2026-09-29T12:00:00Z" } }); await rejects(step(invalidPeriod.result, "review"), invalid("invalid_dates")); });
  await test("bannière matérialisée inactive : placements, CTA, dates, variante et fermeture conservés", async () => { const m = await materialized("banner", { banner: { ...params("banner").banner!, startsAt: "2026-09-29T00:00:00+02:00", endsAt: "2026-10-02T00:00:00+02:00" } }); const ref = db.collection("promoBanners").doc(m.draft.references.bannerId!); const before = (await ref.get()).data()!; equal(before.isActive, false); deepEqual(before.placements, ["shop", "home"]); const a = await step(m, "activate"); equal(a.draft.state, "activated"); const after = (await ref.get()).data()!; equal(after.buttonUrl, "/boutique"); equal(after.variant, "promo"); equal(after.dismissible, true); equal(after.isArchived, false); });
  await test("CTA dangereux ou incomplet et placements invalides bloquent la revue", async () => { for (const change of [{ buttonUrl: "javascript:alert(1)" }, { buttonUrl: "//evil.test" }, { buttonUrl: "https://example.test\\@evil.test" }, { buttonUrl: "" }, { placements: ["draft", "home"] }]) { const f = await setup("banner", { banner: { ...params("banner").banner!, ...change } as NonNullable<MarketingParameters["banner"]> }); await rejects(step(f.result, "review"), invalid("invalid_draft")); } });
  await test("bannière liée inactive bloquée puis active autorisée sans activer son coupon", async () => { const coupon = await materialized(); const linkedCouponId = coupon.draft.references.couponId!; const banner = await materialized("banner", { banner: { ...params("banner").banner!, linkedCouponId } }); await rejects(step(banner, "activate"), invalid("linked_promotion_inactive")); await step(coupon, "activate"); const a = await step(banner, "activate"); equal(a.draft.state, "activated"); equal((await db.collection("coupons").doc(linkedCouponId).get()).data()?.usedCount, 0); });
  await test("bannière liée future autorisée comme programmation, lien expiré refusé", async () => { const future = await materialized("promotion", { promotion: { ...params("promotion").promotion!, startsAt: "2026-09-29T12:00:00Z", endsAt: "2026-10-02T12:00:00Z" } }); await step(future, "activate"); const banner = await materialized("banner", { banner: { ...params("banner").banner!, linkedCouponId: future.draft.references.couponId } }); await step(banner, "activate"); const ref = db.collection("coupons").doc(future.draft.references.couponId!); await ref.update({ startsAt: "2026-09-26T12:00:00Z", endsAt: "2026-09-27T12:00:00Z" }); const expired = await materialized("banner", { banner: { ...params("banner").banner!, linkedCouponId: ref.id } }); await rejects(step(expired, "activate"), invalid("linked_promotion_inactive")); });
  await test("lien manquant, code divergent et coupon concours protégés", async () => { const f = await setup("banner", { banner: { ...params("banner").banner!, linkedCouponId: "missing-coupon" } }); await rejects(step(f.result, "review"), invalid("linked_promotion_missing")); const p = await materialized(); const mismatch = await setup("banner", { banner: { ...params("banner").banner!, linkedCouponId: p.draft.references.couponId, linkedPromoCode: "DIFFERENT" } }); await rejects(step(mismatch.result, "review"), invalid("linked_promotion_conflict")); const id = `prize-${randomUUID()}`; await db.collection("coupons").doc(id).set({ ...params("promotion").promotion, source: "contest", contestPrizeId: "protected", isActive: true, usedCount: 0 }); await rejects(setup("promotion", params("promotion"), { couponId: id }), invalid("protected_coupon")); const protectedBanner = await setup("banner", { banner: { ...params("banner").banner!, linkedCouponId: id } }); await rejects(step(protectedBanner.result, "review"), invalid("protected_coupon")); });
  await test("campagne atomicité : conflit bannière ne laisse aucune promotion active", async () => { const m = await materialized("campaign"); const coupon = db.collection("coupons").doc(m.draft.references.couponId!); const banner = db.collection("promoBanners").doc(m.draft.references.bannerId!); equal((await coupon.get()).data()?.isActive, false); equal((await banner.get()).data()?.isActive, false); await banner.update({ title: "Changement concurrent" }); await rejects(step(m, "activate"), invalid("business_conflict")); equal((await coupon.get()).data()?.isActive, false); equal((await banner.get()).data()?.isActive, false); });
  await test("échec de la seconde écriture : rollback intégral puis reprise avec le même UUID", async () => { const m = await materialized("campaign"); const op = { action: "activate" as const, operationId: randomUUID(), draftId: m.draft.id, expectedRevision: m.draft.revision }; const faulty = { collection: db.collection.bind(db), runTransaction: (run: (tx: Transaction) => Promise<unknown>) => db.runTransaction((tx) => run(new Proxy(tx, { get(target, prop) { if (prop === "update") return (ref: FirebaseFirestore.DocumentReference, data: FirebaseFirestore.UpdateData<FirebaseFirestore.DocumentData>) => { if (ref.path === `promoBanners/${m.draft.references.bannerId}`) throw new Error("simulated second write failure"); return target.update(ref, data); }; const member = Reflect.get(target, prop); return typeof member === "function" ? member.bind(target) : member; } }))) } as unknown as Firestore; await rejects(executeMarketingOperation(faulty, actor, op, now), /second write failure/); equal((await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()?.isActive, false); equal((await db.collection("promoBanners").doc(m.draft.references.bannerId!).get()).data()?.isActive, false); equal((await db.collection("marketingOperations").doc(op.operationId).get()).exists, false); const applied = await executeMarketingOperation(db, actor, op, now); equal(applied.replayed, false); equal((await executeMarketingOperation(db, actor, op, now)).replayed, true); });
  await test("campagne liée et UUID stables, activation et désactivation des deux objets", async () => { const m = await materialized("campaign"); const banner = db.collection("promoBanners").doc(m.draft.references.bannerId!); equal((await banner.get()).data()?.linkedCouponId, m.draft.references.couponId); const a = await step(m, "activate"); equal((await banner.get()).data()?.isActive, true); equal((await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()?.isActive, true); await step(a, "deactivate"); equal((await banner.get()).data()?.isActive, false); equal((await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()?.isActive, false); });
  await test("modèles / archives et placement draft restent non activables", async () => { for (const [kind, parameters] of [["promotion", { promotion: { ...params("promotion").promotion!, isTemplate: true } }], ["banner", { banner: { ...params("banner").banner!, isArchived: true } }], ["banner", { banner: { ...params("banner").banner!, placements: ["draft"], placement: "draft" } }]] as [MarketingKind, MarketingParameters][]) { const m = await materialized(kind, parameters); await rejects(step(m, "activate"), (e: unknown) => e instanceof MarketingError); } });
  await test("code unique et réservation transactionnelle empêchent les doublons", async () => { const parameters = params("promotion"); const first = await approved("promotion", parameters); const second = await approved("promotion", parameters); await step(first, "materialize"); await rejects(step(second, "materialize"), (e: unknown) => e instanceof MarketingError && ["business_conflict", "code_conflict"].includes(e.code)); });
  await test("objet supprimé après matérialisation refusé, aucun recréation silencieuse", async () => { const m = await materialized("campaign"); await db.collection("promoBanners").doc(m.draft.references.bannerId!).delete(); await rejects(step(m, "activate"), invalid("reference_missing")); equal((await db.collection("coupons").doc(m.draft.references.couponId!).get()).data()?.isActive, false); });
  await test("concours : brouillon natif matérialisé sans participants, tirage, récompense ou invitation", async () => { const before = await sizes(["contestEntries", "contestDraws", "contestPrizes", "coupons"]); const m = await materialized("contest"); const native = (await db.collection("contests").doc(m.draft.references.contestId!).get()).data()!; equal(native.status, "draft"); equal(native.entryCount, 0); ok(native.sequenceNumber > 0); deepEqual(await sizes(["contestEntries", "contestDraws", "contestPrizes", "coupons"]), before); const audits = await db.collection("contestAuditLogs").where("contestId", "==", m.draft.references.contestId).get(); equal(audits.docs[0].data().action, "contest_created"); });
  await test("concours programmation explicite rejouable, pas de gain automatique", async () => { const m = await materialized("contest"); const id = randomUUID(); const a = await step(m, "activate", id); equal((await db.collection("contests").doc(m.draft.references.contestId!).get()).data()?.status, "scheduled"); equal(a.draft.state, "activated"); equal((await step(m, "activate", id)).replayed, true); equal((await db.collection("contestDraws").where("contestId", "==", m.draft.references.contestId).get()).size, 0); });
  await test("concours édition de configuration réutilise le moteur sans réécrire entryCount", async () => { const input = contestInput(); const contest = await createContest(db, input, { actorType: "admin", actorId: actor }); await db.collection("contests").doc(contest.id).update({ entryCount: 11 }); const m = await materialized("contest", { contest: { ...input, title: "Nouvelle configuration" } }, { contestId: contest.id }); equal((await db.collection("contests").doc(contest.id).get()).data()?.title, input.title); await step(m, "activate"); const data = (await db.collection("contests").doc(contest.id).get()).data()!; equal(data.title, "Nouvelle configuration"); equal(data.entryCount, 11); });
  await test("concours actif et conflit de période : contrôles natifs et admin conservés", async () => { const input = contestInput(); input.startAt = new Date(now.getTime() - 60000).toISOString(); input.endAt = new Date(now.getTime() + 3600000).toISOString(); input.drawAt = new Date(now.getTime() + 7200000).toISOString(); const m = await materialized("contest", { contest: input }); await step(m, "activate"); const active = (await db.collection("contests").doc(m.draft.references.contestId!).get()).data()!; equal(active.status, "active"); const conflict = await materialized("contest", { contest: { ...input, slug: `other-${randomUUID()}` } }); await rejects(step(conflict, "activate"), invalid("contest_period_conflict")); const edit = await setup("contest", { contest: { ...input, title: "Édition interdite" } }, { contestId: m.draft.references.contestId }); await rejects(step(edit.result, "review"), invalid("contest_configuration_locked")); await transitionContest(db, m.draft.references.contestId!, "cancelled", { actorType: "admin", actorId: actor }, now); });
  await test("concours révision obsolète et règlement invalide refusés", async () => { const m = await materialized("contest"); const edit = await executeMarketingOperation(db, actor, { action: "save", operationId: randomUUID(), draftId: m.draft.id, expectedRevision: 1, title: "Dates modifiées", parameters: { contest: { ...m.draft.parameters.contest!, prizeValue: 45 } } }, now); equal(edit.draft.revision, 2); await rejects(step(m, "activate"), invalid("stale_revision")); const bad = await setup("contest", { contest: { ...contestInput(), rulesText: "", rulesUrl: "" } }); await rejects(step(bad.result, "review")); });
  await test("permissions API : absent / invalide / non-admin / admin désactivé / admin actif", async () => { await db.collection("adminUsers").doc("disabled-marketing-admin").set({ isActive: false }); for (const [token, status] of [["", 401], ["invalid", 401], ["customer", 403], ["disabled-marketing-admin", 403], [actor, 200]] as const) equal((await api(token)).status, status); const f = await setup(); equal((await api("customer", "POST", { action: "activate", operationId: randomUUID(), draftId: f.result.draft.id, expectedRevision: 1 })).status, 403); });
  await test("audit privé cohérent et contexte relie les objets sans statut métier artificiel", async () => { const ctx = await getMarketingContext(db) as { drafts: Array<{ id: string }> }; ok(ctx.drafts.length > 0); const audit = await db.collection("marketingAuditLogs").get(); ok(audit.docs.every((doc) => doc.data().actorId === actor && doc.data().createdAt.toDate() instanceof Date && Number.isInteger(doc.data().revision))); ok(audit.docs.some((doc) => doc.data().contestAuditCollection === "contestAuditLogs")); });
  await test("validations pures ne créent aucun document métier", async () => { const before = await sizes(["coupons", "promoBanners", "contests"]); validateMarketingParameters(params("campaign"), "campaign"); deepEqual(await sizes(["coupons", "promoBanners", "contests"]), before); });
  console.log(`${checks} groupes Marketing/API/transactions validés, uniquement sur l'émulateur officiel.`);
} finally { await db.terminate(); }
