import { equal, deepEqual, ok, rejects, throws } from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Firestore, Transaction } from "firebase-admin/firestore";
import { FieldValue } from "firebase-admin/firestore";
import { request as httpRequest } from "node:http";
import { expectBlockedNetwork } from "./cagnotteNetworkGuard.js";
import { connectCagnotteEmulator, CAGNOTTE_DEMO } from "./cagnotteEmulator.js";
import { commitPipeline, commitSelectionImport, createPipelineHandler, PipelineError, readPipelineContext, type PipelineResult } from "../api/_server/selectionPipeline.js";
import { extractSupplierPage } from "../api/_server/supplierExtraction.js";
import { emptySelection, type ProductSelection } from "../src/types/selection.js";
import { emptyCommercial, type PipelineAction } from "../src/types/selectionPipeline.js";
import { FirebaseIdTokenVerificationError } from "../api/_server/adminAuth.js";
import type { VercelRequestLike, VercelResponseLike } from "../api/_server/http.js";
const db = await connectCagnotteEmulator(CAGNOTTE_DEMO); const admin = { uid: "pipeline-admin" }; let checks = 0;
const test = async (name: string, run: () => Promise<unknown>) => { await run(); checks++; console.log(`PASS ${name}`); };
const images = new Map<string, string>(); const pdfs = new Map<string, string>();
const assets = { readImage: async () => Buffer.from([255, 216, 255]), saveImage: async (path: string, data: string) => { images.set(path, data); }, savePdf: async (path: string, item: ProductSelection) => { pdfs.set(path, item.id); } };
function selection(): ProductSelection { const key = randomUUID(); return { ...emptySelection(), name: `Fleur ${key}`, publicName: `Fleur ${key}`, supplier: "Fournisseur privé", url: `https://originecbd.fr/${key}`, category: "Fleur", origin: "France", taste: "Fruité", aromas: "Fruit", intensity: "moyenne", aromaFamily: "fruite", appearance: "Compact", notes: "note confidentielle", prices: [{ format: "5 g", price: "9.99" }], commercial: { ...emptyCommercial(), description: "Une description de fleur assez longue, validée par l’admin.", pricePerGram: 4, initialStock: 25, seoTitle: "Fleur Verdanza", seoDescription: "Une description fruitée." }, economics: [{ id: "3g", label: "3 g", quantity: 3, unit: "g", cost: 5, costBasis: "HT", costSource: "manual", evidence: "manuel privé", capturedAt: "2026-09-28", finalPrice: 11 }] }; }
async function setup(item = selection()) { const operationId = randomUUID(); const operation = { action: "save", id: "", expectedRevision: 0, operationId, selection: item, imageBase64: "fixture-jpeg" }; const result = await commitPipeline(db, operation, admin, assets); return { result, operation, id: result.selection.id, ref: db.collection("productSelections").doc(result.selection.id), product: db.collection("products").doc(`selection-${result.selection.id}`) }; }
async function reservedSource(id: string) { const sources = await db.collection("selectionSources").where("selectionId", "==", id).get(); equal(sources.size, 1); return sources.docs[0].ref; }
async function step(result: PipelineResult, action: PipelineAction, operationId = randomUUID()) { return commitPipeline(db, { action, id: result.selection.id, expectedRevision: result.selection.revision, operationId }, admin, assets); }
async function prepared() { const f = await setup(); f.result = await step(await step(f.result, "validateSelection"), "prepareProduct"); return f; }
async function catalogue() { const f = await prepared(); f.result = await step(f.result, "createCatalog"); return f; }
try {
  await db.collection("adminUsers").doc(admin.uid).set({ isActive: true });
  await test("URL → brouillon uniquement, zéro écritures Firestore et Storage", async () => { const before = (await db.collection("productSelections").get()).size; const count = images.size; const item = await extractSupplierPage("https://originecbd.fr/local-fixture", { resolve: async () => [{ address: "8.8.8.8", family: 4 }], request: async () => ({ status: 200, contentType: "text/html", body: "<h1>Fleur fixture</h1>", location: "" }) }); equal(item.id, ""); equal((await db.collection("productSelections").get()).size, before); equal(images.size, count); });
  await test("confirmation → sélection privée, nouvelle révision, image après confirmation", async () => { const f = await setup(); equal(f.result.selection.revision, 1); equal(f.result.workflow.revision, 1); equal((await f.ref.get()).data()?.notes, "note confidentielle"); ok(images.has(f.result.selection.imagePath)); equal((await f.product.get()).exists, false); });
  await test("sauvegarde rejouée et réponse perdue : même fiche, même image, même révision", async () => { const f = await setup(); const count = images.size; const replay = await commitPipeline(db, f.operation, admin, assets); equal(replay.selection.id, f.id); equal(replay.selection.revision, 1); equal(replay.replayed, true); equal(images.size, count); await rejects(commitPipeline(db, { ...f.operation, selection: { ...f.operation.selection, name: "changed" } }, admin, assets), (e: unknown) => e instanceof PipelineError && e.status === 409); });
  await test("source inchangée : réservation conservée après édition", async () => {
    const f = await setup(); const source = await reservedSource(f.id);
    const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, notes: "Édition sans changement de source" } }, admin, assets);
    equal(saved.selection.revision, 2); equal((await reservedSource(f.id)).id, source.id); deepEqual((await source.get()).data(), { selectionId: f.id });
  });
  await test("URL A → B : ancienne source libérée et réutilisable, nouvelle réservée", async () => {
    const f = await setup(); const oldSource = await reservedSource(f.id); const oldUrl = f.result.selection.url;
    const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, url: `${oldUrl}-updated` } }, admin, assets);
    equal((await oldSource.get()).exists, false); ok((await reservedSource(f.id)).id !== oldSource.id); equal(saved.selection.url, `${oldUrl}-updated`);
    const replacement = await setup({ ...selection(), url: oldUrl }); equal((await oldSource.get()).data()?.selectionId, replacement.id);
  });
  await test("fallback sans URL : changement de nom ou fournisseur libère l’ancienne clé", async () => {
    for (const field of ["name", "supplier"] as const) {
      const f = await setup({ ...selection(), url: "" }); const oldSource = await reservedSource(f.id);
      const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, [field]: `${f.result.selection[field]} updated` } }, admin, assets);
      equal((await oldSource.get()).exists, false); ok((await reservedSource(f.id)).id !== oldSource.id); equal(saved.selection.url, "");
      const replacement = await setup({ ...selection(), url: "", name: f.result.selection.name, supplier: f.result.selection.supplier }); equal((await oldSource.get()).data()?.selectionId, replacement.id);
    }
  });
  await test("ancienne réservation appartenant à une autre sélection : aucune suppression", async () => {
    const f = await setup(); const other = await setup(); const oldSource = await reservedSource(f.id); const foreign = { selectionId: other.id, marker: "foreign reservation" };
    await oldSource.set(foreign);
    await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, url: `${f.result.selection.url}-updated` } }, admin, assets);
    deepEqual((await oldSource.get()).data(), foreign); ok((await reservedSource(f.id)).id !== oldSource.id);
  });
  await test("collision sur nouvelle source : refus sans perdre réservation, fiche ou workflow", async () => {
    const f = await setup(); const other = await setup(); const oldSource = await reservedSource(f.id); const newSource = await reservedSource(other.id); const operationId = randomUUID();
    const before = (await f.ref.get()).data(); const workflow = db.collection("selectionWorkflows").doc(f.id); const beforeWorkflow = (await workflow.get()).data();
    await rejects(commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId, selection: { ...f.result.selection, url: other.result.selection.url } }, admin, assets), (error: unknown) => error instanceof PipelineError && error.status === 409 && /source possède déjà/.test(error.message));
    deepEqual((await oldSource.get()).data(), { selectionId: f.id }); deepEqual((await newSource.get()).data(), { selectionId: other.id }); deepEqual((await f.ref.get()).data(), before); deepEqual((await workflow.get()).data(), beforeWorkflow); equal((await db.collection("selectionOperations").doc(operationId).get()).exists, false);
  });
  await test("changement de source concurrent et rejeu : une révision, aucun effet répété", async () => {
    const f = await setup(); const oldSource = await reservedSource(f.id); const operationId = randomUUID();
    const operation = { action: "save", id: f.id, expectedRevision: 1, operationId, selection: { ...f.result.selection, url: `${f.result.selection.url}-updated` } };
    const results = await Promise.all([commitPipeline(db, operation, admin, assets), commitPipeline(db, operation, admin, assets)]);
    equal(results.filter((result) => !result.replayed).length, 1); equal(results.filter((result) => result.replayed).length, 1); equal((await f.ref.get()).data()?.revision, 2); equal((await oldSource.get()).exists, false); const newSource = await reservedSource(f.id);
    const replacement = await setup({ ...selection(), url: f.result.selection.url }); const replay = await commitPipeline(db, operation, admin, assets);
    equal(replay.replayed, true); equal(replay.selection.revision, 2); equal((await oldSource.get()).data()?.selectionId, replacement.id); equal((await reservedSource(f.id)).id, newSource.id);
  });
  await test("ancienne sélection sans réservation : changement de source compatible", async () => {
    const f = await setup(); const oldSource = await reservedSource(f.id); await oldSource.delete();
    await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, url: `${f.result.selection.url}-updated` } }, admin, assets);
    equal((await oldSource.get()).exists, false); ok((await reservedSource(f.id)).id !== oldSource.id);
  });
  await test("échec du reçu après changement de source : réservations et fiche rollback", async () => {
    const f = await setup(); const oldSource = await reservedSource(f.id); const before = (await f.ref.get()).data(); const workflow = db.collection("selectionWorkflows").doc(f.id); const beforeWorkflow = (await workflow.get()).data(); const operationId = randomUUID();
    const failing = { collection: db.collection.bind(db), runTransaction: (callback: (tx: Transaction) => Promise<unknown>) => db.runTransaction((tx) => callback(new Proxy(tx, { get(target, key) { if (key === "create") return (ref: FirebaseFirestore.DocumentReference, data: FirebaseFirestore.DocumentData) => { if (ref.parent.id === "selectionOperations") throw new Error("receipt_failure"); return target.create(ref, data); }; const value = Reflect.get(target, key); return typeof value === "function" ? value.bind(target) : value; } }))) } as unknown as Firestore;
    await rejects(commitPipeline(failing, { action: "save", id: f.id, expectedRevision: 1, operationId, selection: { ...f.result.selection, url: `${f.result.selection.url}-updated` } }, admin, assets), /receipt_failure/);
    equal((await reservedSource(f.id)).id, oldSource.id); deepEqual((await oldSource.get()).data(), { selectionId: f.id }); deepEqual((await f.ref.get()).data(), before); deepEqual((await workflow.get()).data(), beforeWorkflow); equal((await db.collection("selectionOperations").doc(operationId).get()).exists, false);
  });
  await test("révision N validée, édition prix/description/format invalide l’aval", async () => { const f = await prepared(); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, commercial: { ...f.result.selection.commercial!, pricePerGram: 5 }, description: "Modifiée" } }, admin, assets); equal(saved.selection.revision, 2); equal(saved.workflow.stale, true); equal(saved.workflow.selectionValidatedRevision, null); equal(saved.workflow.productPreparedRevision, null); await rejects(step(f.result, "createCatalog"), /Révision/); });
  await test("préparation produit privée, coûts/notes absents, aucune activation", async () => { const f = await prepared(); equal((await f.product.get()).exists, false); equal(f.result.workflow.draft?.isActive, false); equal(f.result.workflow.draft?.fixedPriceOptions?.[0].totalPrice, 11); const text = JSON.stringify(f.result.workflow.draft); for (const privateValue of ["note confidentielle", "Fournisseur privé", "originecbd.fr", "manuel privé"]) ok(!text.includes(privateValue)); });
  await test("catalogue créé inactif, référence atomique et projection publique propre", async () => { const f = await catalogue(); const p = (await f.product.get()).data()!; equal(p.isActive, false); equal(p.sourceSelectionId, f.id); equal(p.stock, 25); ok(p.internalReference); equal((await db.collection("productReferences").doc(p.internalReference).get()).data()?.productId, f.product.id); for (const key of ["notes", "prices", "supplier", "economics", "url", "attributes", "extraction"]) equal(key in p, false); });
  await test("activation uniquement après validation finale, stock conservé", async () => { const f = await catalogue(); await rejects(step(f.result, "activate"), /obsolète/); const ready = await step(f.result, "validatePublication"); const active = await step(ready, "activate"); equal((await f.product.get()).data()?.isActive, true); equal((await f.product.get()).data()?.stock, 25); equal(active.workflow.publishedRevision, 1); equal(active.selection.status, "En boutique"); equal((await db.collection("productSelectionSheets").get()).size, 0); });
  await test("double confirmation concurrente : un seul produit et référence", async () => { const f = await prepared(); const op = randomUUID(); const result = await Promise.all([step(f.result, "createCatalog", op), step(f.result, "createCatalog", op)]); equal(result[0].productId, result[1].productId); equal((await db.collection("products").where("sourceSelectionId", "==", f.id).get()).size, 1); equal((await db.collection("productReferences").where("productId", "==", f.product.id).get()).size, 1); });
  await test("rejeu d’activation après vente : aucun stock écrasé ni seconde activation", async () => { const f = await catalogue(); const ready = await step(f.result, "validatePublication"); const op = randomUUID(); await step(ready, "activate", op); await f.product.update({ stock: 19 }); const replay = await step(ready, "activate", op); equal(replay.replayed, true); equal((await f.product.get()).data()?.stock, 19); });
  await test("éditeur ouvert avant activation : sauvegarde périmée refusée sans désactivation", async () => { const f = await catalogue(); const before = f.result.selection; await step(await step(f.result, "validatePublication"), "activate"); await rejects(commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...before, notes: "édition ancienne" } }, admin, assets), /Fiche modifiée/); equal((await f.product.get()).data()?.isActive, true); equal((await f.ref.get()).data()?.status, "En boutique"); });
  await test("stock ou contenu modifié entre validation et activation : refus", async () => { const f = await catalogue(); const ready = await step(f.result, "validatePublication"); await f.product.update({ stock: 20 }); await rejects(step(ready, "activate"), /obsolète/); equal((await f.product.get()).data()?.isActive, false); });
  await test("stock initial nul : création inactive, publication bloquée", async () => { const f = await setup(); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, commercial: { ...f.result.selection.commercial!, initialStock: 0 } } }, admin, assets); const next = await step(await step(await step(saved, "validateSelection"), "prepareProduct"), "createCatalog"); await rejects(step(next, "validatePublication"), /Stock/); });
  await test("produit lié historique inactif : pas de doublon, référence et formats conservés", async () => { const f = await setup(); const legacy = `legacy-${randomUUID()}`; const options = [{ id: "legacy5", quantityGrams: 5, totalPrice: 19, isActive: true, source: "manual", policyVersion: 1 }]; await db.collection("products").doc(legacy).set({ name: "Historique", slug: "historique", category: "flowers", stock: 17, lowStockThreshold: 3, isActive: false, internalReference: "VDZ-000123", fixedPriceMode: "manual", fixedPriceOptions: options }); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, catalogProductId: legacy, economics: [], commercial: { ...f.result.selection.commercial!, initialStock: 99, fixedPriceOptions: [], fixedPriceMode: "disabled" } } }, admin, assets); const p = await step(await step(saved, "validateSelection"), "prepareProduct"); deepEqual(p.workflow.draft?.fixedPriceOptions, options); const c = await step(p, "createCatalog"); equal(c.productId, legacy); equal((await f.product.get()).exists, false); const ready = await step(c, "validatePublication"); await step(ready, "activate"); equal((await db.collection("products").doc(legacy).get()).data()?.stock, 17); equal((await db.collection("products").doc(legacy).get()).data()?.lowStockThreshold, 3); });
  await test("produit actif existant : préparation sans changement public avant confirmation", async () => { const f = await catalogue(); const active = await step(await step(f.result, "validatePublication"), "activate"); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...active.selection, commercial: { ...active.selection.commercial!, pricePerGram: 6 }, economics: active.selection.economics!.map((r) => ({ ...r, finalPrice: 17 })) } }, admin, assets); const c = await step(await step(await step(saved, "validateSelection"), "prepareProduct"), "createCatalog"); equal((await f.product.get()).data()?.price, 4); equal((await f.product.get()).data()?.isActive, true); await step(await step(c, "validatePublication"), "activate"); equal((await f.product.get()).data()?.price, 6); });
  await test("fiche/PDF publique indépendante du produit inactif et idempotente", async () => { const f = await catalogue(); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, status: "En boutique" } }, admin, assets); const op = randomUUID(); const sheet = await step(saved, "publishSheet", op); const count = pdfs.size; equal((await f.product.get()).data()?.isActive, false); ok(sheet.selection.publishedSlug); equal((await db.collection("productSelectionSheets").doc(sheet.selection.publishedSlug).get()).exists, true); await step(saved, "publishSheet", op); equal(pdfs.size, count); await step(sheet, "unpublishSheet"); equal((await f.product.get()).data()?.isActive, false); });
  await test("import parallèle même URL : une sélection, aucun produit", async () => { const item = selection(); const settled = await Promise.allSettled([commitPipeline(db, { action: "save", operationId: randomUUID(), id: "", expectedRevision: 0, selection: item }, admin, assets), commitPipeline(db, { action: "save", operationId: randomUUID(), id: "", expectedRevision: 0, selection: item }, admin, assets)]); equal(settled.filter((r) => r.status === "fulfilled").length, 1); equal((await db.collection("productSelections").where("url", "==", item.url).get()).size, 1); });
  await test("import JSON atomique, doublons/rejeu, pas de source publique importée", async () => { const item = { ...selection(), catalogProductId: "forged", imagePath: "forged", publishedSlug: "forged" }; const op = randomUUID(); const result = await commitSelectionImport(db, [item, item], op, admin); equal(result.imported, 1); equal(result.skipped, 1); deepEqual(await commitSelectionImport(db, [item, item], op, admin), result); const saved = (await db.collection("productSelections").where("url", "==", item.url).get()).docs[0].data(); equal(saved.catalogProductId, ""); equal(saved.imagePath, ""); equal(saved.publishedSlug, ""); });
  await test("référence conflictuelle, lien étranger et produit protégé refusés", async () => { const f = await prepared(); await f.product.set({ sourceSelectionId: "other", isActive: false }); await rejects(step(f.result, "createCatalog"), /autre sélection/); await f.product.set({ sourceSelectionId: f.id, isActive: false, internalReference: "VDZ-FLR-ABCDEF" }); await db.collection("productReferences").doc("VDZ-FLR-ABCDEF").set({ productId: "other" }); await rejects(step(f.result, "createCatalog"), /Référence/); await f.product.update({ productionFixture: {} }); await rejects(step(f.result, "createCatalog"), /protégé/); });
  await test("échec du reçu transactionnel : produit/référence/workflow rollback", async () => { const f = await prepared(); const failing = { collection: db.collection.bind(db), runTransaction: (callback: (tx: Transaction) => Promise<unknown>) => db.runTransaction((tx) => callback(new Proxy(tx, { get(target, key) { if (key === "create") return (ref: FirebaseFirestore.DocumentReference, data: FirebaseFirestore.DocumentData) => { if (ref.parent.id === "selectionOperations") throw new Error("receipt_failure"); return target.create(ref, data); }; const value = Reflect.get(target, key); return typeof value === "function" ? value.bind(target) : value; } }))) } as unknown as Firestore; await rejects(commitPipeline(failing, { action: "createCatalog", id: f.id, expectedRevision: 1, operationId: randomUUID() }, admin, assets), /receipt_failure/); equal((await f.product.get()).exists, false); equal((await db.collection("productReferences").where("productId", "==", f.product.id).get()).size, 0); });
  await test("contexte privé autoritatif et anciennes sélections consultables sans migration", async () => { const id = `old-${randomUUID()}`; await db.collection("productSelections").doc(id).set({ ...selection(), id }); const context = await readPipelineContext(db, id); equal(context.workflow.revision, 0); equal(context.workflow.draft, null); equal(context.catalogue.available, true); equal(context.policy, null); equal((await db.collection("selectionWorkflows").doc(id).get()).exists, false); });
  await test("image publique figée et galerie préservée jusqu’à publication finale", async () => {
    const f = await catalogue(); const active = await step(await step(f.result, "validatePublication"), "activate"); const oldPath = active.selection.imagePath;
    await f.product.update({ selectionImagePath: FieldValue.delete(), images: [{ id: "legacy-photo", url: "/images/fixture-gallery.jpg", alt: "Galerie", isPrimary: true, sortOrder: 0 }], qualitySealEnabled: true });
    const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), imageBase64: "new-fixture-image", selection: active.selection }, admin, assets);
    ok(saved.selection.imagePath !== oldPath); equal((await f.product.get()).data()?.selectionImagePath, oldPath);
    const c = await step(await step(await step(saved, "validateSelection"), "prepareProduct"), "createCatalog"); equal(c.workflow.draft?.images?.length, 2); equal((await f.product.get()).data()?.selectionImagePath, oldPath);
    await step(await step(c, "validatePublication"), "activate"); equal((await f.product.get()).data()?.selectionImagePath, saved.selection.imagePath); equal((await f.product.get()).data()?.qualitySealEnabled, true);
  });
  await test("projection historique nettoyée sans perte : snapshot privé avant publication", async () => { const f = await catalogue(); await f.product.update({ supplier: "private legacy supplier", notes: "private legacy note", purchasePricePerGram: 1.5, unknownField: "private" }); const result = await step(await step(f.result, "validatePublication"), "activate"); const p = (await f.product.get()).data()!; for (const key of ["supplier", "notes", "purchasePricePerGram", "unknownField"]) equal(key in p, false); equal(result.workflow.legacyProductSnapshot?.notes, "private legacy note"); equal(p.stock, 25); });
  await test("galerie complète compatible : image principale remplacée, vues secondaires conservées", async () => { const f = await setup(); const legacy = `gallery-${randomUUID()}`; const images = [{ id: "old-primary", url: "/old-main.jpg", alt: "Ancienne principale", isPrimary: true, sortOrder: 0 }, { id: "secondary-one", url: "/secondary-one.jpg", alt: "Vue 1", isPrimary: false, sortOrder: 1 }, { id: "secondary-two", url: "/secondary-two.jpg", alt: "Vue 2", isPrimary: false, sortOrder: 2 }]; await db.collection("products").doc(legacy).set({ name: "Galerie", slug: "galerie", category: "flowers", stock: 17, isActive: false, images, image: "/old-main.jpg" }); const saved = await commitPipeline(db, { action: "save", id: f.id, expectedRevision: 1, operationId: randomUUID(), selection: { ...f.result.selection, catalogProductId: legacy } }, admin, assets); const p = await step(await step(saved, "validateSelection"), "prepareProduct"); equal(p.workflow.draft?.images?.length, 3); deepEqual(p.workflow.draft?.images?.slice(1).map((i) => i.url), ["/secondary-one.jpg", "/secondary-two.jpg"]); const result = await step(await step(await step(p, "createCatalog"), "validatePublication"), "activate"); deepEqual(result.workflow.legacyProductSnapshot?.images, images); });
  await test("source legacy sans réservation et adresse produit conflictuelle refusées", async () => { const item = selection(); await db.collection("productSelections").doc(`legacy-${randomUUID()}`).set(item); await rejects(commitPipeline(db, { action: "save", id: "", expectedRevision: 0, operationId: randomUUID(), selection: item }, admin, assets), /ancienne sélection/); const f = await prepared(); await db.collection("products").doc(`conflict-${randomUUID()}`).set({ slug: f.result.workflow.draft!.slug, isActive: false }); await rejects(step(f.result, "createCatalog"), /Adresse produit/); equal((await f.product.get()).exists, false); });
  await test("politique privée confirmée, rejeu et conflit sans changement de prix public", async () => {
    const policy = { schemaVersion: 1, category: "flowers", positioning: "standard", targetContributionRate: .4, variableRate: .1, packagingCost: .2, lossRate: 0, costBasis: "HT", sellingBasis: "TTC", taxRate: .2, roundingIncrement: .1, roundingMode: "up" };
    const handler = createPipelineHandler({ getDb: () => db, verifyToken: async () => ({ uid: admin.uid, email: null }), assets });
    const call = async (body: unknown) => { let status = 200; const response = { setHeader() {}, status(value: number) { status = value; return this; }, json() {} }; await handler({ method: "POST", url: "/api/selection", headers: { authorization: "Bearer fixture" }, body } as VercelRequestLike, response as unknown as VercelResponseLike); return status; };
    const body = { action: "pipelinePolicy", operationId: randomUUID(), expectedPolicy: null, policy };
    equal(await call(body), 200); equal(await call(body), 200); equal(await call({ ...body, operationId: randomUUID() }), 409); equal(await call({ ...body, operationId: randomUUID(), policy: { ...policy, taxRate: null } }), 400);
    const stored = await db.collection("selectionPricingPolicies").doc("flowers-standard").get(); equal(stored.data()?.targetContributionRate, .4);
  });
  await test("port secondaire strict : Production et autre port de boucle locale bloqués", async () => { equal(CAGNOTTE_DEMO.port, 18086); expectBlockedNetwork(() => throws(() => httpRequest("http://127.0.0.1:18085/"), /TEST_NETWORK_BLOCKED/)); expectBlockedNetwork(() => throws(() => httpRequest("https://firestore.googleapis.com/"), /TEST_NETWORK_BLOCKED/)); });
  await test("API strictement admin, jeton absent/invalide et administrateur inactif", async () => { const handler = createPipelineHandler({ getDb: () => db, verifyToken: async (token) => { if (token === "invalid") throw new FirebaseIdTokenVerificationError("authentication"); return { uid: token, email: null }; }, assets }); for (const [token, expected] of [["", 401], ["invalid", 401], ["customer", 403], [admin.uid, 200]] as const) { const f = await setup(); let status = 200; const response = { setHeader() {}, status(value: number) { status = value; return this; }, json() {} }; await handler({ method: "GET", url: `/api/selection?action=pipeline&id=${f.id}`, headers: token ? { authorization: `Bearer ${token}` } : {} } as VercelRequestLike, response as unknown as VercelResponseLike); equal(status, expected); } });
  console.log(`${checks} groupes pipeline/API/transactions validés sur émulateur, Storage simulé.`);
} finally { await db.terminate(); }
